name: CMake

on:
  push:
    branches: [ master, separate-include-source-dir ]
  pull_request:
    branches: [ master ]

env:
  CMAKE_BUILD_TYPE: Release
  CMAKE_GENERATOR: Ninja

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2022, ubuntu-24.04 ]
        compiler: [ msvc, gcc, clang ]
        exclude:
          - os: windows-2022
            compiler: gcc
          - os: ubuntu-24.04
            compiler: msvc

    steps:
    - uses: actions/checkout@v4
  
    - name: Install ninja
      run: |
           sudo apt update
           sudo apt install ninja-build
      if: matrix.os == 'ubuntu-24.04'
    
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake (gcc)
      working-directory: ${{github.workspace}}/build
      run: cmake -S ${{github.workspace}} -DCMAKE_C_COMPILER=gcc-13 -DCMAKE_CXX_COMPILER=g++-13
      if: matrix.os == 'ubuntu-24.04' && matrix.compiler == 'gcc'
    
    - name: Configure CMake (clang)
      working-directory: ${{github.workspace}}/build
      run: cmake -S ${{github.workspace}} -DCMAKE_C_COMPILER=clang-18 -DCMAKE_CXX_COMPILER=clang++-18
      if: matrix.os == 'ubuntu-24.04' && matrix.compiler == 'clang'
      
    - name: Configure CMake (msvc)
      working-directory: ${{github.workspace}}/build
      shell: pwsh
      run:  |
            ${{github.workspace}}/setup_vsdev.ps1
            cmake -S ${{github.workspace}} -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl
      if: matrix.os == 'windows-2022' && matrix.compiler == 'msvc'
    
    - name: Configure CMake (clang-cl)
      working-directory: ${{github.workspace}}/build
      shell: pwsh
      run:  |
            ${{github.workspace}}/setup_vsdev.ps1
            cmake -S ${{github.workspace}} -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl
      if: matrix.os == 'windows-2022' && matrix.compiler == 'clang'

    - name: Build (windows)
      working-directory: ${{github.workspace}}/build
      shell: pwsh
      run:  |
            ${{github.workspace}}/setup_vsdev.ps1
            cmake --build ${{github.workspace}}/build --config ${{env.CMAKE_BUILD_TYPE}}
      if: matrix.os == 'windows-2022'
    
    - name: Build (linux)
      working-directory: ${{github.workspace}}/build
      run: cmake --build ${{github.workspace}}/build --config ${{env.CMAKE_BUILD_TYPE}}
      if: matrix.os == 'ubuntu-24.04'

    - name: Test
      working-directory: ${{github.workspace}}/build/Tests
      run: ctest --rerun-failed --output-on-failure -C ${{env.CMAKE_BUILD_TYPE}}
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ARLib-${{matrix.os}}-${{matrix.compiler}}
        path: ${{github.workspace}}/build/ARLib.lib
      if: matrix.os == 'windows-2022'
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ARLib-${{matrix.os}}-${{matrix.compiler}}
        path: ${{github.workspace}}/build/libARLib.a
      if: matrix.os == 'ubuntu-24.04'